categories: [bugbounty, crypto, for, misc, prog, pwn, re, web, quest]
directories: [server-files, public-files, exploit, src]
files:
  bin: [build, deploy, Dockerfile, exploit/exploit]
  config: {challenge: mkctf.yml}
  txt: [writeup.md, public-files/description.md]
flag: {prefix: 'INSA{', suffix: '}'}
name: INS'hAck 2018
