categories: [bugbounty, crypto, for, misc, prog, pwn, re, web, quest]
directories: 
  public: [public-files]
  private: [server-files, exploit, src]
files:
  bin: [build, deploy, exploit/exploit]
  config: {challenge: .mkctf.yml}
  txt: [writeup.md, Dockerfile, public-files/description.md]
flag: {prefix: 'INSA{', suffix: '}'}
name: INS'hAck 2018
