---
- name: Set up multiple authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - ../files/hugo
    - ../files/leo-ovh-mba
    - ../files/leo-mbp
    - ../files/mgmt
